---
version: '3.7'
services:

  crawler:
    image: lucmichalski/car-crawler:latest
    container_name: ${NAMESPACE}-crawler  
    build: .
    ports:
    - 9000:9000
    networks:
    - internal
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
    - ./dataset:/opt/lucmichalski/bin/datasets
    - cache-data:/opt/lucmichalski/bin/data
    - public-data:/opt/lucmichalski/bin/public
    restart: unless-stopped
    depends_on:
    - mysql
    links:
    - mysql:mysql

  mysql:
    image: mysql:5.7
    container_name: ${NAMESPACE}-db
    ports:
    - 13306:3306
    volumes:
    - db-data:/var/lib/mysql
    networks:
    - internal
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    restart: unless-stopped

  imaginary:
    image: h2non/imaginary:latest
    container_name: ${NAMESPACE}_imaginary
    volumes:
    - imaginary-data:/mnt/data
    environment:
       PORT: 9002
    ports:
    - "9002:9002"
    networks:
    - internal
    command: -cors -gzip -enable-url-source -mount /mnt/data
    restart: unless-stopped

  sidekiq: &darknet_base
    build:
      context: .docker/darknet
    image: go-darknet:latest
    working_dir: /darknet
    volumes:
    - ./darknet:/darknet
    - darknet-data:/darknet/models
    command: ./scripts/download_data.sh

  darknet:
    <<: *darknet_base
    ports:
    - "9003:9003"
    restart: unless-stopped
    # command: ["/bin/bash"]
    command: go run server.go --configFile=models/yolov3.cfg --weightsFile=models/yolov3.weights
    networks:
    - internal
    - web # for tests purpose    

  gocv:
    image: lucmichalski/gocv:alpine-cpu-latest
    build:
      context: .docker/gocv-alpine
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}-gocv
    ports:
    - 8099:8099
    networks:
    - internal
    - web # for tests purpose
    restart: unless-stopped

  find-object:
    image: lucmichalski/find-object:alpine-cpu-latest
    build:
      context: .docker/find-object
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}-findobj
    ports:
    - 8100:8100
    networks:
    - internal
    - web # for tests purpose
    restart: unless-stopped
    # command [""]

networks:
  internal:
  web:
    external: true

volumes:
  db-data:
  cache-data:
  imaginary-data:
  darknet-data:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/models
  public-data:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/public
