apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: backup
  name: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: backup
    spec:
      containers:
      - env:
        - name: BACKUP_METHOD
          value: mysqldump
        - name: MYSQL_DATABASE
          value: dataset_cars
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PASSWORD
          value: supercar
        - name: MYSQL_USER
          value: cars
        - name: SCHEDULE
          value: 0 0 0 3 *
        - name: TIMEZONE
        image: zeenlym/mariadb-backup
        imagePullPolicy: ""
        name: -backup
        resources: {}
        volumeMounts:
        - mountPath: /backup
          name: backup-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: backup-claim0
        persistentVolumeClaim:
          claimName: backup-claim0
status: {}
