apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: crawler
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: crawler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: crawler
    spec:
      containers:
      - args:
        - cars-dataset
        - --parallel-jobs
        - "1"
        env:
        - name: MYSQL_DATABASE
          value: dataset_cars
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PASSWORD
          value: supercar
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: cars
        image: lucmichalski/car-crawler:latest
        imagePullPolicy: ""
        name: -crawler
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /opt/lucmichalski/bin/datasets
          name: crawler-claim0
        - mountPath: /tmp
          name: crawler-claim1
        - mountPath: /opt/lucmichalski/bin/data
          name: cache-data
        - mountPath: /opt/lucmichalski/bin/public
          name: public-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: crawler-claim0
        persistentVolumeClaim:
          claimName: crawler-claim0
      - name: crawler-claim1
        persistentVolumeClaim:
          claimName: crawler-claim1
      - name: cache-data
        persistentVolumeClaim:
          claimName: cache-data
      - name: public-data
        persistentVolumeClaim:
          claimName: public-data
status: {}
