apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: darknet
  name: darknet
spec:
  ports:
  - name: "9003"
    port: 9003
    targetPort: 9003
  selector:
    io.kompose.service: darknet
status:
  loadBalancer: {}
