apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: protonvpn
  name: protonvpn
spec:
  ports:
  - name: "1080"
    port: 1080
    targetPort: 1080
  selector:
    io.kompose.service: protonvpn
status:
  loadBalancer: {}
