apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium
  name: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: selenium
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.network/web: "true"
        io.kompose.service: selenium
    spec:
      containers:
      - image: selenium/standalone-chrome:latest
        imagePullPolicy: ""
        name: selenium
        ports:
        - containerPort: 4444
        resources: {}
        volumeMounts:
        - mountPath: /dev/shm
          name: selenium-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: selenium-claim0
        persistentVolumeClaim:
          claimName: selenium-claim0
status: {}
